package sk.apupo.shoppinglist.daos;

import sk.apupo.shoppinglist.daos.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PRODUCT.
 */
public class Product {

    private String title;
    private String description;
    private Float unitPrice;
    private Boolean bought;
    private java.util.Date boughtDate;
    private java.util.Date modificationDate;
    private String titleClean;
    private Boolean inBasket;
    private Integer quantity;
    private Integer quantityType;
    private long fk_category_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ProductDao myDao;

    private CategoryEntity categoryEntity;
    private Long categoryEntity__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Product() {
    }

    public Product(String title, String description, Float unitPrice, Boolean bought, java.util.Date boughtDate, java.util.Date modificationDate, String titleClean, Boolean inBasket, Integer quantity, Integer quantityType, long fk_category_id) {
        this.title = title;
        this.description = description;
        this.unitPrice = unitPrice;
        this.bought = bought;
        this.boughtDate = boughtDate;
        this.modificationDate = modificationDate;
        this.titleClean = titleClean;
        this.inBasket = inBasket;
        this.quantity = quantity;
        this.quantityType = quantityType;
        this.fk_category_id = fk_category_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getProductDao() : null;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Float getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Float unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Boolean getBought() {
        return bought;
    }

    public void setBought(Boolean bought) {
        this.bought = bought;
    }

    public java.util.Date getBoughtDate() {
        return boughtDate;
    }

    public void setBoughtDate(java.util.Date boughtDate) {
        this.boughtDate = boughtDate;
    }

    public java.util.Date getModificationDate() {
        return modificationDate;
    }

    public void setModificationDate(java.util.Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    public String getTitleClean() {
        return titleClean;
    }

    public void setTitleClean(String titleClean) {
        this.titleClean = titleClean;
    }

    public Boolean getInBasket() {
        return inBasket;
    }

    public void setInBasket(Boolean inBasket) {
        this.inBasket = inBasket;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Integer getQuantityType() {
        return quantityType;
    }

    public void setQuantityType(Integer quantityType) {
        this.quantityType = quantityType;
    }

    public long getFk_category_id() {
        return fk_category_id;
    }

    public void setFk_category_id(long fk_category_id) {
        this.fk_category_id = fk_category_id;
    }

    /** To-one relationship, resolved on first access. */
    public CategoryEntity getCategoryEntity() {
        long __key = this.fk_category_id;
        if (categoryEntity__resolvedKey == null || !categoryEntity__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CategoryEntityDao targetDao = daoSession.getCategoryEntityDao();
            CategoryEntity categoryEntityNew = targetDao.load(__key);
            synchronized (this) {
                categoryEntity = categoryEntityNew;
            	categoryEntity__resolvedKey = __key;
            }
        }
        return categoryEntity;
    }

    public void setCategoryEntity(CategoryEntity categoryEntity) {
        if (categoryEntity == null) {
            throw new DaoException("To-one property 'fk_category_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.categoryEntity = categoryEntity;
            fk_category_id = categoryEntity.getId();
            categoryEntity__resolvedKey = fk_category_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
