package sk.apupo.shoppinglist.daos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import sk.apupo.shoppinglist.daos.Product;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PRODUCT.
*/
public class ProductDao extends AbstractDao<Product, Void> {

    public static final String TABLENAME = "PRODUCT";

    /**
     * Properties of entity Product.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Title = new Property(0, String.class, "title", false, "TITLE");
        public final static Property TitleClean = new Property(1, String.class, "titleClean", false, "TITLE_CLEAN");
        public final static Property MainGroup = new Property(2, String.class, "mainGroup", false, "MAIN_GROUP");
        public final static Property SubGroup = new Property(3, String.class, "subGroup", false, "SUB_GROUP");
        public final static Property Comodity = new Property(4, String.class, "comodity", false, "COMODITY");
        public final static Property SubComodity = new Property(5, String.class, "subComodity", false, "SUB_COMODITY");
        public final static Property ModificationDate = new Property(6, java.util.Date.class, "modificationDate", false, "MODIFICATION_DATE");
        public final static Property InBasket = new Property(7, Boolean.class, "inBasket", false, "IN_BASKET");
        public final static Property Fk_category_id = new Property(8, long.class, "fk_category_id", false, "FK_CATEGORY_ID");
    };

    private DaoSession daoSession;

    private Query<Product> categoryEntity_ProductsQuery;

    public ProductDao(DaoConfig config) {
        super(config);
    }
    
    public ProductDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PRODUCT' (" + //
                "'TITLE' TEXT," + // 0: title
                "'TITLE_CLEAN' TEXT," + // 1: titleClean
                "'MAIN_GROUP' TEXT," + // 2: mainGroup
                "'SUB_GROUP' TEXT," + // 3: subGroup
                "'COMODITY' TEXT," + // 4: comodity
                "'SUB_COMODITY' TEXT," + // 5: subComodity
                "'MODIFICATION_DATE' INTEGER," + // 6: modificationDate
                "'IN_BASKET' INTEGER," + // 7: inBasket
                "'FK_CATEGORY_ID' INTEGER NOT NULL );"); // 8: fk_category_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PRODUCT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Product entity) {
        stmt.clearBindings();
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(1, title);
        }
 
        String titleClean = entity.getTitleClean();
        if (titleClean != null) {
            stmt.bindString(2, titleClean);
        }
 
        String mainGroup = entity.getMainGroup();
        if (mainGroup != null) {
            stmt.bindString(3, mainGroup);
        }
 
        String subGroup = entity.getSubGroup();
        if (subGroup != null) {
            stmt.bindString(4, subGroup);
        }
 
        String comodity = entity.getComodity();
        if (comodity != null) {
            stmt.bindString(5, comodity);
        }
 
        String subComodity = entity.getSubComodity();
        if (subComodity != null) {
            stmt.bindString(6, subComodity);
        }
 
        java.util.Date modificationDate = entity.getModificationDate();
        if (modificationDate != null) {
            stmt.bindLong(7, modificationDate.getTime());
        }
 
        Boolean inBasket = entity.getInBasket();
        if (inBasket != null) {
            stmt.bindLong(8, inBasket ? 1l: 0l);
        }
        stmt.bindLong(9, entity.getFk_category_id());
    }

    @Override
    protected void attachEntity(Product entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Product readEntity(Cursor cursor, int offset) {
        Product entity = new Product( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // title
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // titleClean
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mainGroup
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // subGroup
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // comodity
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // subComodity
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // modificationDate
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // inBasket
            cursor.getLong(offset + 8) // fk_category_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Product entity, int offset) {
        entity.setTitle(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitleClean(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMainGroup(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSubGroup(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setComodity(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSubComodity(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setModificationDate(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setInBasket(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setFk_category_id(cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Product entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Product entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "products" to-many relationship of CategoryEntity. */
    public List<Product> _queryCategoryEntity_Products(long fk_category_id) {
        synchronized (this) {
            if (categoryEntity_ProductsQuery == null) {
                QueryBuilder<Product> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Fk_category_id.eq(null));
                categoryEntity_ProductsQuery = queryBuilder.build();
            }
        }
        Query<Product> query = categoryEntity_ProductsQuery.forCurrentThread();
        query.setParameter(0, fk_category_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCategoryEntityDao().getAllColumns());
            builder.append(" FROM PRODUCT T");
            builder.append(" LEFT JOIN CATEGORY_ENTITY T0 ON T.'FK_CATEGORY_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Product loadCurrentDeep(Cursor cursor, boolean lock) {
        Product entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CategoryEntity categoryEntity = loadCurrentOther(daoSession.getCategoryEntityDao(), cursor, offset);
         if(categoryEntity != null) {
            entity.setCategoryEntity(categoryEntity);
        }

        return entity;    
    }

    public Product loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Product> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Product> list = new ArrayList<Product>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Product> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Product> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
