package sk.apupo.shoppinglist.models.daos;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BASIC_ENTITY.
 */
public class BasicEntity {

    private Boolean deletedLogical;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BasicEntity() {
    }

    public BasicEntity(Boolean deletedLogical) {
        this.deletedLogical = deletedLogical;
    }

    public Boolean getDeletedLogical() {
        return deletedLogical;
    }

    public void setDeletedLogical(Boolean deletedLogical) {
        this.deletedLogical = deletedLogical;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
