package sk.apupo.shoppinglist.models.daos;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig basicEntityDaoConfig;
    private final DaoConfig productEntityDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig categoryEntityDaoConfig;
    private final DaoConfig shoppingListEntityDaoConfig;

    private final BasicEntityDao basicEntityDao;
    private final ProductEntityDao productEntityDao;
    private final ProductDao productDao;
    private final CategoryEntityDao categoryEntityDao;
    private final ShoppingListEntityDao shoppingListEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        basicEntityDaoConfig = daoConfigMap.get(BasicEntityDao.class).clone();
        basicEntityDaoConfig.initIdentityScope(type);

        productEntityDaoConfig = daoConfigMap.get(ProductEntityDao.class).clone();
        productEntityDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        categoryEntityDaoConfig = daoConfigMap.get(CategoryEntityDao.class).clone();
        categoryEntityDaoConfig.initIdentityScope(type);

        shoppingListEntityDaoConfig = daoConfigMap.get(ShoppingListEntityDao.class).clone();
        shoppingListEntityDaoConfig.initIdentityScope(type);

        basicEntityDao = new BasicEntityDao(basicEntityDaoConfig, this);
        productEntityDao = new ProductEntityDao(productEntityDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        categoryEntityDao = new CategoryEntityDao(categoryEntityDaoConfig, this);
        shoppingListEntityDao = new ShoppingListEntityDao(shoppingListEntityDaoConfig, this);

        registerDao(BasicEntity.class, basicEntityDao);
        registerDao(ProductEntity.class, productEntityDao);
        registerDao(Product.class, productDao);
        registerDao(CategoryEntity.class, categoryEntityDao);
        registerDao(ShoppingListEntity.class, shoppingListEntityDao);
    }
    
    public void clear() {
        basicEntityDaoConfig.getIdentityScope().clear();
        productEntityDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        categoryEntityDaoConfig.getIdentityScope().clear();
        shoppingListEntityDaoConfig.getIdentityScope().clear();
    }

    public BasicEntityDao getBasicEntityDao() {
        return basicEntityDao;
    }

    public ProductEntityDao getProductEntityDao() {
        return productEntityDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public CategoryEntityDao getCategoryEntityDao() {
        return categoryEntityDao;
    }

    public ShoppingListEntityDao getShoppingListEntityDao() {
        return shoppingListEntityDao;
    }

}
