package com.apupo.shoppinglist;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PRODUCT_ENTITY.
 */
public class ProductEntity extends BasicEntity  {

    private Long id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ProductEntity() {
    }

    public ProductEntity(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
